apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-server
spec:
  selector:
    app: backend-server
  ports:
    - name: http
      protocol: TCP
      port: 6000
      targetPort: 5000
  type: NodePort
